### ISSUE TITLE
Первая задача

### ISSUE THREAD

**Issue by wldmr-key** [Geoorool/EnterCost#1]
Техническое задание пора бы сформулировать...
Хотя бы по существу

**Comment by Geoorool** [comment]
[ТЗ.docx](https://github.com/Geoorool/EnterCost/files/2398617/default.docx)

**Comment by wldmr-key** [comment]
неплохо, но обращаю внимание на нюансы:

> 2.1. Назначение системы 
> Разрабатываемая система предназначается для упрощения расчета 

то есть системе дается расчет и она его упрощает? не так ведь! Она его делает - в этом ее назначение

> 2.2. Перечень объектов автоматизации (объектов), на которых предполагается её использовать

В каком ГОСТе ты нашел такой подраздел? поделись...

> Цели создания системы 

приемлемо, но придирчивый читатель вспомнит, что достижение цели должно быть объективно измеримо

> 3.1. Краткие сведения об объекте автоматизации

Мало, очень мало. К тому же здесь перемешана информация об объекте автоматизации (предприятие и процесс ценообразования) и о будущей системе (ее, ведь, нет еще?)

> 4.1. Требования к функциям (задачам), выполняемым системой

Слова "форма" и "возможность" в этом контексте нехороши. Понятно, почему?
Проверь еще раз полноту критичных для системы функций

**Comment by Geoorool** [comment]
Исправил, закинул в папку документация
Не совсем уверен в "целях создания", добавил всего одну строчку объективности, ибо больше ничего придумать не получилось
